import { LegalPage } from "@/components/LegalPage";

export const metadata = { title: "Terms & Conditions" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms & Conditions" updated="9 July 2026">
      <p>
        These terms govern your use of digitalmmm (&ldquo;the Service&rdquo;), operated by
        digitalmmm (&ldquo;we&rdquo;, &ldquo;us&rdquo;). By creating an account you agree to them. If you
        don&apos;t agree, don&apos;t use the Service.
      </p>

      <h2>1. The Service</h2>
      <p>
        digitalmmm generates digital products (ebooks, workbooks, planners and, over time,
        other formats) from material you provide, using AI models. Output quality depends
        on your input; we don&apos;t guarantee any particular commercial result from products
        you create.
      </p>

      <h2>2. Your account</h2>
      <ul>
        <li>You must be at least 16 years old and provide accurate information.</li>
        <li>You&apos;re responsible for activity under your account. Keep your credentials secure.</li>
        <li>We may suspend accounts that violate the <a href="/legal/acceptable-use">Acceptable Use Policy</a>.</li>
      </ul>

      <h2>3. Content ownership and commercial rights</h2>
      <ul>
        <li>You retain ownership of the material you upload (source PDFs, URLs, topics).</li>
        <li>
          You own the products you generate and may use and sell them commercially, on
          every plan including Free. Free-plan exports carry a digitalmmm watermark.
        </li>
        <li>
          You are responsible for ensuring your source material doesn&apos;t infringe third-party
          rights, and for any marketplace-specific obligations (for example, Amazon KDP&apos;s
          AI-content declaration) when you publish.
        </li>
        <li>
          By default we do <strong>not</strong> use your content or generations to train AI models.
        </li>
      </ul>

      <h2>4. Plans, credits and billing</h2>
      <ul>
        <li>Paid plans are billed monthly through Stripe. We never see or store card numbers.</li>
        <li>Credits meter generation and refill monthly; unused credits don&apos;t roll over.</li>
        <li>
          Price-lock guarantee: your subscription price will not increase while your
          subscription remains active.
        </li>
        <li>Refunds are handled per the <a href="/legal/refunds">Refund Policy</a>.</li>
      </ul>

      <h2>5. AI-generated content</h2>
      <p>
        Generated content may contain errors. Review everything before you publish or rely
        on it. Exports include machine-readable metadata identifying them as AI-generated,
        in line with EU AI Act transparency obligations — see the{" "}
        <a href="/legal/ai-disclosure">AI Disclosure</a> page. Nothing generated by the
        Service is legal, financial, medical or other professional advice.
      </p>

      <h2>6. Referral program</h2>
      <p>
        Referrers earn a flat 20% of a referred user&apos;s first payment only. Self-referrals,
        fraudulent signups, or misleading promotion (including undisclosed advertising)
        void commissions.
      </p>

      <h2>7. Liability</h2>
      <p>
        The Service is provided &ldquo;as is&rdquo;. To the maximum extent permitted by law, our
        total liability for any claim is limited to the amount you paid us in the 12
        months before the claim arose. Nothing in these terms limits liability that
        cannot legally be limited, or your statutory rights as a consumer.
      </p>

      <h2>8. Termination</h2>
      <p>
        You can delete your account at any time from Settings, which permanently removes
        your data. We may terminate accounts for material breach of these terms with
        notice where practicable.
      </p>

      <h2>9. Changes</h2>
      <p>
        We may update these terms; material changes will be announced by email or in-app
        at least 14 days before they take effect.
      </p>

      <h2>10. Contact</h2>
      <p>support@digitalmmm.com</p>
    </LegalPage>
  );
}
